import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-montserrat antialiased">
        {/* Grid Pattern Background */}
        <div className="fixed inset-0 pointer-events-none opacity-[0.1] bg-grid-pattern z-0" />
        
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
